# Generated by Django 3.2.7 on 2023-03-19 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ctdt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('access', models.CharField(choices=[('0', 'Cơ bản'), ('1', 'Cơ sở'), ('2', 'Chuyên ngành')], default='0', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='subject',
            fields=[
                ('numsub', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('fkctdt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Base.ctdt')),
            ],
        ),
        migrations.AddField(
            model_name='ctdt',
            name='fkmajor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Base.major'),
        ),
    ]
