# Generated by Django 3.2.7 on 2023-03-19 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0002_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='avatar.svg', null=True, upload_to='avatars'),
        ),
    ]
