# Generated by Django 3.2.7 on 2023-03-19 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0003_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='avatar.svg', null=True, upload_to='avatars/{{name}}'),
        ),
    ]
