# Generated by Django 3.2.7 on 2023-03-19 14:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0005_auto_20230319_1757'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.AddField(
            model_name='chapter',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chapter',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
