# Generated by Django 3.2.7 on 2023-03-21 02:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0006_auto_20230319_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='participants', to=settings.AUTH_USER_MODEL),
        ),
    ]
