# Generated by Django 3.2.7 on 2023-03-22 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0009_auto_20230322_0927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='fkmajor',
        ),
        migrations.AddField(
            model_name='subject',
            name='fkctdt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Base.ctdt'),
        ),
    ]
