# Generated by Django 3.2.7 on 2023-03-24 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0010_auto_20230322_0931'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
    ]
