# Generated by Django 3.2.7 on 2023-03-24 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0013_alter_file_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={},
        ),
        migrations.RemoveField(
            model_name='file',
            name='created',
        ),
        migrations.RemoveField(
            model_name='file',
            name='updated',
        ),
    ]
