# Generated by Django 3.2.7 on 2023-03-30 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0016_auto_20230330_1956'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
