# Generated by Django 3.2.7 on 2023-03-30 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0017_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctdt',
            name='fkdepartment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Base.department'),
        ),
    ]
