# Generated by Django 3.2.7 on 2023-03-30 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0018_ctdt_fkdepartment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('fksubject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Base.subject')),
            ],
        ),
        migrations.CreateModel(
            name='ChoiceQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200, null=True)),
                ('op1', models.CharField(max_length=200, null=True)),
                ('op2', models.CharField(max_length=200, null=True)),
                ('op3', models.CharField(max_length=200, null=True)),
                ('op4', models.CharField(max_length=200, null=True)),
                ('ans', models.CharField(max_length=200, null=True)),
                ('fktest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Base.test')),
            ],
        ),
    ]
