# Generated by Django 3.2.7 on 2023-03-30 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0020_evaluate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluate',
            name='point',
            field=models.IntegerField(),
        ),
    ]
